author: Maksim Smirnov

title: Maksim Smirnov

baseurl: ""

url: https://smirnoffmg.github.io
github_username: smirnoffmg

# Contact info
email: "smirnoffmg@gmail.com"
linkedin: "hello-maksim-smirnov"
github: smirnoffmg
telegram: "smirnov_maksim_grigorevich"
description: "Maksim Smirnov CV"

# Google Analytics
google_analytics: G-4HG9NVZRVF

# Yandex Metrika
yandex_metrika: 105809801

# Remote theme
remote_theme: smirnoffmg/harvard-style-cv-theme
